### ISSUE TITLE
bug with multi-carets

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_bootstrap_complete#1]
1. copy the following text to Cud editor (html lexer) and place multi-carets like this:

```html
<a class=| ></a>
<a class=| ></a>
```

2. insert one double-quotes char -> `"`
3. press ctrl+space
4. choose `accordion`

you will see that  double-quotes char was replaced and everything after it!

![image](https://user-images.githubusercontent.com/275333/192598674-1618d6ae-c69e-4862-b884-030641902c46.png)

**Comment by Alexey-T** [comment]
confirmed.

**Comment by Alexey-T** [comment]
confirmed.

**Comment by Alexey-T** [comment]
tried to change code. and was lost in code. sorry. but fix is possible- if we will adjust the text near multi-carets in on_complete(). we can adjust txt like this-

- if only opening quote is present - add closing quote (before showing completion)
- if both opening/closing quotes absent - add both of them

I don't have will to make this
