### ISSUE TITLE
 Add the HTML format feature in the listbox

### ISSUE THREAD

**Issue by eltonfabricio10** [CudaText-addons/cuda_bootstrap_complete#5]

**Comment by veksha** [comment]
could you please provide more information, @eltonfabricio10?
what listbox? completion listbox? how is it going to work?

**Comment by eltonfabricio10** [comment]
Yep, completion listbox

**Comment by veksha** [comment]
I thought you meant formatting of the whole document, but I guess you were talking about bold text.
