### ISSUE TITLE
regression with HTML formatted items

### ISSUE THREAD

**Issue by CudaText-addons** [CudaText-addons/cuda_bootstrap_complete#7]
`<div class="jumbotron text-c|enter">`

choose in completion item 'text-capitalize'. ->

`<div class="jumbotron <html><b>text-c</b>apitalize">`

@veksha a regression.

**Comment by CudaText-addons** [comment]
@veksha, I am fixing it

**Comment by veksha** [comment]
nice! my bad 😨
